services:
  # backend:
  #   # build: .
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     DATABASE_URL: ${DATABASE_URL}
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - database
  database:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: database
