services:
  backend:
    build: .
    container_name: node
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${PRODUCTION_DATABASE_URL}
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate dev --name dev && npm run start:prod"
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: database
